# Generated by Django 3.2.7 on 2023-08-13 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20230806_0129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('-updated', '-created')},
        ),
    ]
